[tool.black]
line-length = 100
target-version = ["py313"]

[tool.ruff]
line-length = 100
target-version = "py313"
extend-select = ["E","F","I","W","UP"]
# 필요 시 무시 규칙 예: ignore = ["E203","E266"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"
